vim.opt.title = true
vim.opt.bg=dark
vim.opt.mouse= 'a'
vim.opt.hlsearch = false
vim.opt.clipboard = 'unnamedplus'
vim.opt.showmode = false
vim.opt.ruler = false
vim.opt.showcmd = false
vim.opt.cursorline = true
vim.opt.smartindent = true
vim.opt.cc = "100"
vim.opt.scrolloff = 8
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.compatible = false
vim.opt.encoding = "utf-8"
vim.opt.wildmode = { 'longest', 'list', 'full' }
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
